|AS Number|AS Description|
| 1299 | TWELVE99 Twelve99, Telia Carrier, SE |
| 2914 | NTT-COMMUNICATIONS-2914, US |
| 3320 | DTAG Internet service provider operations, DE |
| 3356 | LEVEL3, US |
| 4637 | ASN-TELSTRA-GLOBAL Telstra Global, HK |
| 4755 | TATACOMM-AS TATA Communications formerly VSNL is Leading ISP, IN |
| 5603 | SIOL-NET Telekom Slovenije d.d., SI |
| 6453 | AS6453, US |
| 6939 | HURRICANE, US |
| 9498 | BBIL-AP BHARTI Airtel Ltd., IN |
| 12414 | NL-SOLCON SOLCON, NL |
| 14061 | DIGITALOCEAN-ASN, US |
| 34779 | T-2-AS AS set propagated by T-2 d.o.o., SI |
| 198644 | GO6, SI |
