|AS Number|AS Description|Comment|
| 174 | COGENT-174, US | Tier-1 |
| 267 | NETHER-NET, US |  |
| 1299 | TWELVE99 Arelion, fka Telia Carrier, SE | Tier-1 |
| 2497 | IIJ Internet Initiative Japan Inc., JP |  |
| 2828 | XO-AS15, US | Regional Tier |
| 2914 | NTT-LTD-2914, US | Tier-1 |
| 3257 | GTT-BACKBONE GTT, US | Tier-1 |
| 3320 | DTAG Internet service provider operations, DE | Tier-1 |
| 3356 | LEVEL3, US | Tier-1 |
| 3491 | BTN-ASN, US | Tier-1 |
| 4134 | CHINANET-BACKBONE No.31,Jin-rong Street, CN | Regional Tier |
| 4637 | ASN-TELSTRA-GLOBAL Telstra Global, HK | Regional Tier |
| 4755 | TATACOMM-AS TATA Communications formerly VSNL is Leading ISP, IN |  |
| 4788 | TMNET-AS-AP TM Net, Internet Service Provider, MY |  |
| 5511 | OPENTRANSIT, FR | Tier-1 |
| 5603 | SIOL-NET Telekom Slovenije d.d., SI |  |
| 6453 | AS6453, US | Tier-1 |
| 6461 | ZAYO-6461 | Tier-1 |
| 6762 | SEABONE-NET TELECOM ITALIA SPARKLE S.p.A., IT | Tier-1 |
| 6895 | ESPANIX Neutral Interconect Exchange for Spain, ES |  |
| 6939 | HURRICANE, US | Regional Tier |
| 7195 | EDGEUNO SAS, CO |  |
| 8447 | A1TELEKOM-AT A1 Telekom Austria AG, AT |  |
| 9498 | BBIL-AP BHARTI Airtel Ltd., IN |  |
| 12129 | 123NET, US |  |
| 12414 | NL-SOLCON SOLCON, NL |  |
| 14061 | DIGITALOCEAN-ASN, US |  |
| 14103 | ACDNET-ASN1, US |  |
| 16276 | OVH, FR |  |
| 20473 | AS-CHOOPA, US |  |
| 21283 | A1SI-AS A1 Slovenija, SI |  |
| 23889 | MauritiusTelecom, MU |  |
| 33764 | AFRINIC-ZA-JNB-AS, MU |  |
| 34779 | T-2-AS AS set propagated by T-2 d.o.o., SI |  |
| 37100 | SEACOM-AS, MU |  |
| 37271 | Workonline |  |
| 37684 | ANGANI-AS, KE |  |
| 37708 | AFRINIC-MAIN, MU |  |
| 44684 | MYTHIC Mythic Beasts Ltd, GB |  |
| 58461 | CT-HANGZHOU-IDC No.288,Fu-chun Road, CN |  |
| 60011 | MYTHIC-BEASTS-USA, GB |  |
| 198644 | GO6, SI |  |
| 211722 | Nullroute |  |
| 328578 | KEMNET-TECHNOLOGIES-AS, KE |  |
