|AS Number|AS description|
|  1299|TWELVE99 Arelion, fka Telia Carrier, SE|
|  5511|OPENTRANSIT, FR|
|  6895|ESPANIX Neutral Interconect Exchange for Spain, ES|
|  6939|HURRICANE, US|
|  7195|EDGEUNO (DE-CIX Frankfurt)|
|  9498|BBIL-AP BHARTI Airtel Ltd. (Equinix Hong Kong)|
| 14061|DIGITALOCEAN (DE-CIX Frankfurt)|
| 16276|OVH|
| 37684|ANGANI-AS, KE|
| 58461|CT-HANGZHOU-IDC No.288,Fu-chun Road, CN|
|328578|KEMNET-TECHNOLOGIES-AS, KE|
