|AS Number|Tier-1|AS Description|Drop RH0|
| 1299 |yes| TWELVE99 Twelve99, Telia Carrier, SE ||
| 2914 |yes| NTT-COMMUNICATIONS-2914, US ||
| 3320 |yes| DTAG Internet service provider operations, DE ||
| 3356 |yes| LEVEL3, US ||
|4637|regional|ASN-TELSTRA-GLOBAL Telstra Global, HK|drop|
| 4755 ||TATACOMM-AS TATA Communications formerly VSNL is Leading ISP, IN ||
| 6453 |yes| AS6453, US ||
|6939|regional|HURRICANE, US|drop|
| 9498 || BBIL-AP BHARTI Airtel Ltd., IN ||
| 14061 || DIGITALOCEAN-ASN, US ||
