|ASN|AS Name|Country code|Location|
|7195|Edge Uno|AG|Buenos Aires|
|12414|NL-SOLCON SOLCON|NL|Amsterdam|
|14061|Digital Ocean|CA|Toronto, ON|
|14061|Digital Ocean|USA|New York City, NY|
|14601|Digital Ocean|DE|Francfort|
|14601|Digital Ocean|IN|Bangalore|
|14601|Digital Ocean|SG|Singapore|
|16276|OVH|AU|Sydney|
|16276|OVH|PL|Warsaw|
|44684|Mythic Beasts |UK|Cambridge|
|47853|Hostinger|US|Ashville, NC|
|60011|MYTHIC-BEASTS-USA|US|Fremont, CA|
|198644|GO6|SI|Ljubljana|
