|ASN|AS Name|Country code|Location|
|267|NETHER-NET|US|Southfield, MI|
|3764|AFRINIC-Ops|ZA|Johanesburg|
|4134|Chine Telecom|CN|Beijing|
|7195|Edge Uno|AR|Buenos Aires|
|12414|NL-SOLCON SOLCON|NL|Amsterdam|
|14061|Digital Ocean|CA|Toronto, ON|
|14061|Digital Ocean|USA|New York City, NY|
|14601|Digital Ocean|DE|Francfort|
|14601|Digital Ocean|IN|Bangalore|
|14601|Digital Ocean|SG|Singapore|
|14601|Digital Ocean|UK|London|
|16276|OVH|AU|Sydney|
|16276|OVH|PL|Warsaw|
|20473|The Constant Company (Vultr)|MX|Mexico|
|20473|The Constant Company (Vultr)|SP|Madrid|
|20473|The Constant Company (Vultr)|JP|Tokyo|
|37684|Angani|KE|Nairobi|
|37708|AfriNIC Corporate Network|MU|Ebène|
|44684|Mythic Beasts |UK|Cambridge|
|60011|MYTHIC-BEASTS-USA|US|Fremont, CA|
|198644|GO6|SI|Ljubljana|
